# Generated by Django 4.1 on 2023-03-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="All_social_media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_logo", models.CharField(default=None, max_length=255)),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Business_card_social_media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_logo", models.CharField(default=None, max_length=255)),
                ("name", models.CharField(max_length=25)),
                ("id_user", models.IntegerField(default=None)),
                ("link", models.CharField(default=None, max_length=80)),
                ("phone_number", models.BigIntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Entreprise_social_media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_logo", models.CharField(default=None, max_length=255)),
                ("name", models.CharField(max_length=25)),
                ("id_user", models.IntegerField(default=None)),
                ("link", models.CharField(default=None, max_length=80)),
                ("id_entreprise", models.IntegerField(default=None)),
                ("phone_number", models.BigIntegerField(default=None, null=True)),
            ],
        ),
    ]
