# Generated by Django 4.1 on 2023-03-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_all_in_one", "0002_userconfirmation"),
    ]

    operations = [
        migrations.CreateModel(
            name="telephonie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=25)),
                ("indicateur", models.CharField(max_length=10)),
                ("nb_chiffres", models.IntegerField(default=None)),
            ],
        ),
    ]
