# Generated by Django 4.1 on 2023-03-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_all_in_one", "0003_telephonie"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_additional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(default=None, max_length=254)),
                (
                    "path_profil",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("job", models.CharField(default=None, max_length=20, null=True)),
                (
                    "job_description",
                    models.CharField(default=None, max_length=150, null=True),
                ),
            ],
        ),
    ]
