# Generated by Django 4.1 on 2023-03-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_all_in_one", "0004_user_additional"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_user", models.IntegerField(default=None)),
                ("secteur", models.CharField(max_length=25)),
                ("nom_entreprise", models.CharField(max_length=40)),
                ("statut", models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="Secteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle_secteur", models.CharField(max_length=25)),
            ],
        ),
    ]
