# Generated by Django 4.1 on 2023-03-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_all_in_one", "0006_business_card_social_media_indicateur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_qrcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=25)),
                ("path", models.CharField(default=None, max_length=255)),
                ("modele", models.CharField(default=None, max_length=255)),
                ("flag_plaque", models.IntegerField(default=None)),
                ("flag_business_card", models.IntegerField(default=None)),
                ("id_user", models.IntegerField(default=None)),
                ("id_entreprise", models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name="user_additional",
            name="job",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user_additional",
            name="job_description",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
