# Generated by Django 4.1 on 2023-03-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_all_in_one", "0007_user_qrcode_alter_user_additional_job_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_additional",
            name="folder_path",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
